// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ChatProtocol.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GNSPrac.Chat
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatProtocol : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public MsgType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name_change")]
        public NameChange NameChange
        {
            get => __pbn__msg.Is(2) ? ((NameChange)__pbn__msg.Object) : default;
            set => __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeNameChange() => __pbn__msg.Is(2);
        public void ResetNameChange() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__msg;

        [global::ProtoBuf.ProtoMember(3, Name = @"chat")]
        public Chat Chat
        {
            get => __pbn__msg.Is(3) ? ((Chat)__pbn__msg.Object) : default;
            set => __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeChat() => __pbn__msg.Is(3);
        public void ResetChat() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 3);

        [global::ProtoBuf.ProtoContract()]
        public enum MsgType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MSG_TYPE_UNSPECIFIED")]
            MsgTypeUnspecified = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MSG_TYPE_NAME_CHANGE")]
            MsgTypeNameChange = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MSG_TYPE_CHAT")]
            MsgTypeChat = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NameChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Chat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
